name: Add Contributor

on:
  pull_request:
    types: [opened]

jobs:
  add-contributor:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Validate PR
      run: |
        if ! grep -q "\- \[.*\](https:\/\/github.com\/.*)" CONTRIBUTORS.md; then
          echo "The CONTRIBUTORS.md file has not been updated correctly."
          exit 1
        fi

    - name: Add Comment on PR
      uses: actions/github-script@v6
      with:
        script: |
          const issueComment = context.payload.pull_request.body.includes('- [')
            ? "Thank you for contributing! Everything looks great 🎉."
            : "Please make sure to add your name in the correct format to the CONTRIBUTORS.md file.";
          github.rest.issues.createComment({
            issue_number: context.payload.pull_request.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: issueComment,
          });
